source 'https://github.com/CocoaPods/Specs.git'

FRAMEWORK_NAME = 'AUTTheming'
PODSPEC_PATH = './'
# Target Names
TESTS_TARGET_NAME = 'Tests'
THEMING_SYMBOLS_GENERATOR_TARGET_NAME = 'AUTThemingSymbolsGenerator'
BUTTONS_EXAMPLE_TARGET_NAME = 'ButtonsExample'
DYNAMIC_THEMES_EXAMPLE_TARGET_NAME = 'DynamicThemesExample'
SWIFT_BUTTONS_EXAMPLE_TARGET_NAME = 'SwiftButtonsExample'
# Paths
EXAMPLES_FOLDER = 'Examples'
BUTTONS_EXAMPLE_PATH = "#{EXAMPLES_FOLDER}/#{BUTTONS_EXAMPLE_TARGET_NAME}"
DYNAMIC_THEMES_EXAMPLE_PATH = "#{EXAMPLES_FOLDER}/#{DYNAMIC_THEMES_EXAMPLE_TARGET_NAME}"
SWIFT_BUTTONS_EXAMPLE_PATH = "#{EXAMPLES_FOLDER}/#{SWIFT_BUTTONS_EXAMPLE_TARGET_NAME}"
THEMING_SYMBOLS_GENERATOR_PATH = "#{THEMING_SYMBOLS_GENERATOR_TARGET_NAME}/#{THEMING_SYMBOLS_GENERATOR_TARGET_NAME}"

workspace FRAMEWORK_NAME

xcodeproj BUTTONS_EXAMPLE_PATH
target BUTTONS_EXAMPLE_TARGET_NAME do
  platform :ios, '8.0'
  xcodeproj BUTTONS_EXAMPLE_PATH
  pod 'Masonry'
end

xcodeproj DYNAMIC_THEMES_EXAMPLE_PATH
target DYNAMIC_THEMES_EXAMPLE_TARGET_NAME do
  platform :ios, '8.0'
  xcodeproj DYNAMIC_THEMES_EXAMPLE_PATH
  pod 'Masonry'
end

xcodeproj THEMING_SYMBOLS_GENERATOR_PATH
target THEMING_SYMBOLS_GENERATOR_TARGET_NAME do
  platform :osx, '10.8'
  xcodeproj THEMING_SYMBOLS_GENERATOR_PATH
  pod 'GBCli'
end
