//
//  GBOptionsHelper+ThemingSymbolsGenerator.m
//  AUTThemingSymbolsGenerator
//
//  Created by Eric Horacek on 12/28/14.
//  Copyright (c) 2014 Automatic Labs, Inc. All rights reserved.
//

#import "GBOptionsHelper+ThemingSymbolsGenerator.h"
#import "GBSettings+ThemingSymbolsGenerator.h"

@implementation GBOptionsHelper (ThemingSymbolsGenerator)

- (void)aut_registerOptions
{
    [self registerOption:'t'
                    long:AUTSettingsOptionThemes
             description:@"The JSON theme file(s) to generate symbols from. You may specify more than one theme by using this parameter more than once (e.g. -t [theme1.json] -t [theme2.json])."
                   flags:GBOptionRequiredValue];
    
    [self registerOption:'o'
                    long:AUTSettingsOptionOutput
             description:@"The symbol files output path. Defaults to the current working directory."
                   flags:GBOptionRequiredValue];
    
    [self registerOption:'p'
                    long:AUTSettingsOptionPrefix
             description:@"The prefix for the symbols generated by this tool. Defaults to 'AUT'."
                   flags:GBOptionOptionalValue];
    
    [self registerOption:'a'
                    long:AUTSettingsOptionTabs
             description:@"Indent the generated symbol files using tabs, rather than spaces (the default)."
                   flags:GBOptionNoValue];
    
    [self registerOption:'i'
                    long:AUTSettingsOptionIndentationCount
             description:@"The number of characters that should be used to indent struct members in the symbols files. Defaults to 4."
                   flags:GBOptionNoValue];
    
    [self registerOption:'h'
                    long:AUTSettingsOptionHelp
             description:@"Display this help message and exit."
                   flags:GBOptionNoValue];
    
    [self registerOption:'v'
                    long:AUTSettingsOptionVerbose
             description:@"Print output verbosely when executing."
                   flags:GBOptionNoValue];
}

@end
